#!/bin/sh
  ssh  -i /var/lib/jenkins/.ssh/id_rsa -tv app@54.209.25.107 <<EOF
  cd ~
  git clone https://d96627b98a4893abc81c2738b983b247e731bdfb@github.com/dotmcduffie/ 
  cd ~/hello-jenkins
  npm install --production
 ./scrpt/test 
  exit
EOF
